// Package sink writes deterministic Records resources to a generic OGC Records API.
package sink

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/rand/v2"
	"net/http"
	"net/url"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/SomethingCreativeStudios/hronir/internal/config"
	"github.com/SomethingCreativeStudios/hronir/internal/model"
	"github.com/SomethingCreativeStudios/hronir/internal/transport"
)

type Sink interface {
	Check(context.Context) error
	Get(context.Context, string) (model.Record, bool, error)
	Put(context.Context, string, model.Record) error
	Delete(context.Context, string) error
}
type HTTP struct {
	base      *url.URL
	catalogID string
	client    *http.Client
}

func NewHTTP(ctx context.Context, target config.TargetConfig, timeout time.Duration) (*HTTP, error) {
	base, err := url.Parse(target.URL)
	if err != nil {
		return nil, err
	}
	client, err := transport.HTTPClient(ctx, target.Auth, target.TLS, timeout)
	if err != nil {
		return nil, err
	}
	return &HTTP{base: base, catalogID: target.CatalogID, client: client}, nil
}
func (h *HTTP) Check(ctx context.Context) error {
	var doc map[string]any
	if err := h.doJSON(ctx, http.MethodGet, h.catalogURL(), nil, &doc); err != nil {
		return fmt.Errorf("target catalog preflight: %w", err)
	}
	supported, ok := doc["supportsNonAutogeneratedResourceIds"].(bool)
	if !ok || !supported {
		return errors.New("target catalog does not advertise supportsNonAutogeneratedResourceIds=true")
	}
	return nil
}
func (h *HTTP) Get(ctx context.Context, id string) (model.Record, bool, error) {
	var record model.Record
	err := h.doJSON(ctx, http.MethodGet, h.itemURL(id), nil, &record)
	if errors.Is(err, ErrNotFound) {
		return nil, false, nil
	}
	return record, err == nil, err
}
func (h *HTTP) Put(ctx context.Context, id string, record model.Record) error {
	return h.doJSON(ctx, http.MethodPut, h.itemURL(id), record, nil)
}
func (h *HTTP) Delete(ctx context.Context, id string) error {
	err := h.doJSON(ctx, http.MethodDelete, h.itemURL(id), nil, nil)
	if errors.Is(err, ErrNotFound) {
		return nil
	}
	return err
}
func (h *HTTP) catalogURL() *url.URL { return h.relative("collections/" + url.PathEscape(h.catalogID)) }
func (h *HTTP) itemURL(id string) *url.URL {
	return h.relative("collections/" + url.PathEscape(h.catalogID) + "/items/" + url.PathEscape(id))
}
func (h *HTTP) relative(suffix string) *url.URL {
	clone := *h.base
	clone.Path = path.Join(strings.TrimSuffix(h.base.Path, "/"), suffix)
	return &clone
}
func (h *HTTP) doJSON(ctx context.Context, method string, target *url.URL, body any, destination any) error {
	var encoded []byte
	var err error
	if body != nil {
		encoded, err = json.Marshal(body)
		if err != nil {
			return err
		}
	}
	for attempt := 0; attempt < 4; attempt++ {
		var reader io.Reader
		if encoded != nil {
			reader = bytes.NewReader(encoded)
		}
		request, err := http.NewRequestWithContext(ctx, method, target.String(), reader)
		if err != nil {
			return err
		}
		request.Header.Set("Accept", "application/geo+json, application/json;q=0.9")
		if encoded != nil {
			request.Header.Set("Content-Type", "application/geo+json")
		}
		response, err := h.client.Do(request)
		if err != nil {
			if retryableError(err) && attempt < 3 {
				if err := wait(ctx, attempt, 0); err != nil {
					return err
				}
				continue
			}
			return err
		}
		data, readErr := io.ReadAll(io.LimitReader(response.Body, 8<<20))
		response.Body.Close()
		if readErr != nil {
			return readErr
		}
		if response.StatusCode == http.StatusNotFound {
			return ErrNotFound
		}
		if response.StatusCode >= 200 && response.StatusCode < 300 {
			if destination != nil && len(data) > 0 {
				if err := json.Unmarshal(data, destination); err != nil {
					return err
				}
			}
			return nil
		}
		if (response.StatusCode == 429 || response.StatusCode >= 500) && attempt < 3 {
			if err := wait(ctx, attempt, retryAfter(response)); err != nil {
				return err
			}
			continue
		}
		return fmt.Errorf("%s %s: HTTP %d: %s", method, target, response.StatusCode, strings.TrimSpace(string(data)))
	}
	return errors.New("retry loop exhausted")
}

var ErrNotFound = errors.New("record not found")

func retryableError(error) bool { return true }
func retryAfter(response *http.Response) time.Duration {
	if raw := response.Header.Get("Retry-After"); raw != "" {
		if seconds, err := strconv.Atoi(raw); err == nil && seconds >= 0 {
			return time.Duration(seconds) * time.Second
		}
	}
	return 0
}
func wait(ctx context.Context, attempt int, server time.Duration) error {
	delay := server
	if delay <= 0 {
		delay = time.Duration(1<<attempt)*200*time.Millisecond + time.Duration(rand.IntN(150))*time.Millisecond
	}
	timer := time.NewTimer(delay)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}
