package sink

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/SomethingCreativeStudios/hronir/internal/config"
	"github.com/SomethingCreativeStudios/hronir/internal/model"
)

func TestCheckAndDeterministicPut(t *testing.T) {
	var gotID string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/collections/connected-systems" {
			_, _ = w.Write([]byte(`{"supportsNonAutogeneratedResourceIds":true}`))
			return
		}
		gotID = r.URL.Path
		if r.Method == http.MethodPut {
			w.WriteHeader(http.StatusCreated)
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer server.Close()
	target, err := NewHTTP(context.Background(), config.TargetConfig{URL: server.URL, CatalogID: "connected-systems"}, time.Second)
	if err != nil {
		t.Fatal(err)
	}
	if err := target.Check(context.Background()); err != nil {
		t.Fatal(err)
	}
	if err := target.Put(context.Background(), "stable", model.Record{"id": "stable", "type": "Feature", "geometry": nil, "properties": map[string]any{"type": "system"}}); err != nil {
		t.Fatal(err)
	}
	if gotID != "/collections/connected-systems/items/stable" {
		t.Fatalf("unexpected item URL %s", gotID)
	}
}
