package harvest

import (
	"context"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"sync/atomic"
	"testing"

	"github.com/SomethingCreativeStudios/hronir/internal/config"
	"github.com/SomethingCreativeStudios/hronir/internal/mapping"
	"github.com/SomethingCreativeStudios/hronir/internal/sink"
	"github.com/SomethingCreativeStudios/hronir/internal/state"
)

func TestSyncDoesNotRewriteUnchangedResource(t *testing.T) {
	var puts atomic.Int32
	sourceServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" {
			_, _ = w.Write([]byte(`{"links":[]}`))
			return
		}
		_, _ = w.Write([]byte(`{"features":[{"id":"one","properties":{"name":"One"},"geometry":null}]}`))
	}))
	defer sourceServer.Close()
	targetServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/collections/connected-systems" {
			_, _ = w.Write([]byte(`{"supportsNonAutogeneratedResourceIds":true}`))
			return
		}
		if r.Method == http.MethodPut {
			puts.Add(1)
			w.WriteHeader(201)
			return
		}
		w.WriteHeader(404)
	}))
	defer targetServer.Close()
	cfg := config.Config{APIVersion: config.APIVersion, Kind: config.Kind, Target: config.TargetConfig{URL: targetServer.URL, CatalogID: "connected-systems"}, State: config.StateConfig{Path: filepath.Join(t.TempDir(), "state.db")}, Sources: []config.SourceConfig{{ID: "primary", URL: sourceServer.URL, Resources: map[string]config.ResourceConfig{"systems": {Mode: "auto"}}}}}
	if err := cfg.NormalizeAndValidate(); err != nil {
		t.Fatal(err)
	}
	store, err := state.Open(cfg.State.Path)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	mapper, err := mapping.New(cfg.Mapping)
	if err != nil {
		t.Fatal(err)
	}
	target, err := sink.NewHTTP(context.Background(), cfg.Target, cfg.Runtime.RequestTimeout)
	if err != nil {
		t.Fatal(err)
	}
	coordinator := New(cfg, store, mapper, target, nil, nil)
	if err := coordinator.Sync(context.Background(), "", "systems"); err != nil {
		t.Fatal(err)
	}
	if err := coordinator.Sync(context.Background(), "", "systems"); err != nil {
		t.Fatal(err)
	}
	if puts.Load() != 1 {
		t.Fatalf("expected one PUT, got %d", puts.Load())
	}
}
